#! /bin/sh

# autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &

# monitor layout
#xrandr --output DP-0 --pos 0x0 --output DP-2 --pos 1920x0 # two monitors
xrandr --output DP-2 --pos 0x0 # single right monitor
xrandr --output DP-0 --off

# compositor for transitions and opacity
picom --config ~/.config/picom/picom.conf &

# wallpaper, bar colors and polybar
$HOME/.config/polybar/shapes/scripts/pywal.sh $HOME/.config/deewarKaghaz
$HOME/.config/polybar/launch.sh --shapes &

#bspc monitor DP-0 -d I II III IV V
#bspc monitor DP-2 -d VI VII VIII IX X
bspc monitor DP-2 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
#bspc rule -a Emacs desktop='^3'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bash /home/sadan/.config/bspwm/bspwm_colors.sh &
